phishstats:
  base_url: "https://api.phishstats.info/api/phishing"
  limit: 500
  pages: 1
  queries:
    - name: general
      filter: ""
    - name: facebook
      filter: "_where=(url,like,~facebook~)&_sort=-id"
    - name: google
      filter: "_where=(url,like,~google~)&_sort=-id"
      